apiVersion: v1
kind: Service
metadata:
  name: postgres-event
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: postgres-event
  ports:
    - port: 5432
      targetPort: 5432
