sonar.projectKey=unige-pinfo6-2026_unige-events-frontend
sonar.projectName=unige-events-frontend
sonar.organization=unige-pinfo6-2026
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/*.test.ts,**/*.test.tsx,src/__tests__/setup.ts,dist/**,**/*.d.ts,src/bones/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
