package ch.unige.events.report.entity;

import ch.unige.events.shared.domain.enums.ReportReason;
import ch.unige.events.shared.domain.enums.ReportStatus;
import io.quarkus.hibernate.orm.panache.PanacheEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Index;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import org.hibernate.annotations.Check;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Owned by moderation-service. Carbon-copy of legacy
 * ch.unige.events.entity.Report.
 *
 * <p>Décision F finalization-ultimate (STUB-001): cross-service
 * navigations to {@code event} / {@code reporter} / {@code reviewedBy}
 * are replaced by id-only columns. Underlying foreign keys still point
 * at {@code events(id)} / {@code users(id)} of the shared schema —
 * only JPA navigation goes away. Enrichment of event title / reporter
 * displayName is performed at the service layer via REST clients.
 *
 * <p>SCRUM-144 — schema étendu pour les reports de commentaires :
 * <ul>
 *   <li>{@code eventId} devient nullable (était NOT NULL). Renseigné quand
 *       la cible est un event, {@code null} quand la cible est un commentaire.</li>
 *   <li>{@code commentId} ajouté, nullable. Renseigné quand la cible est un
 *       commentaire ; mutuellement exclusif avec {@code eventId}.</li>
 *   <li>La CHECK contraint {@code report_target_xor} côté DB enforce le XOR
 *       strict : un report cible <strong>exactement</strong> un event OU un
 *       commentaire. Les UKs partielles {@code uq_report_event_partial} +
 *       {@code uq_report_comment_partial} (V4) protègent les doublons par
 *       cible. L'ancienne UK {@code uk_report_reporter_event} est droppée.</li>
 * </ul>
 *
 * <p>Les contraintes UK partielles ne sont pas déclarables via JPA
 * {@code @UniqueConstraint} (qui ne supporte pas la clause {@code WHERE}) —
 * elles vivent uniquement côté DB via la migration V4.
 */
@Entity
@Table(
        name = "reports",
        indexes = {
                @Index(name = "idx_report_event", columnList = "event_id"),
                @Index(name = "idx_report_comment", columnList = "comment_id"),
                @Index(name = "idx_report_status", columnList = "status")
        }
)
// {@link Check} carries the XOR constraint into the schema generated by
// %test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
// so {@code ReportEntityXorSentinelTest} can exercise it without Flyway
// (which is disabled in %test). The Sonar S1874 deprecation warning is
// a false positive on Hibernate 6.x — the annotation is fully supported
// and recommended for table-scoped CHECKs since the JPA standard has no
// equivalent (cf. Hibernate 6.4 user guide § 2.6.10).
@SuppressWarnings("java:S1874")
@Check(
        name = "report_target_xor",
        constraints = "(event_id IS NULL) <> (comment_id IS NULL)"
)
public class Report extends PanacheEntity {

    @Column(name = "event_id")
    public Long eventId;

    @Column(name = "comment_id")
    public Long commentId;

    @Column(name = "reporter_id")
    public UUID reporterId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 32)
    public ReportReason reason;

    @Column(columnDefinition = "TEXT")
    public String description;

    @Enumerated(EnumType.STRING)
    @Column(columnDefinition = "varchar(255)", nullable = false)
    public ReportStatus status = ReportStatus.PENDING;

    @Column(name = "moderation_note", columnDefinition = "TEXT")
    public String moderationNote;

    @Column(name = "reviewed_at")
    public LocalDateTime reviewedAt;

    @Column(name = "reviewed_by")
    public UUID reviewedById;

    @Column(updatable = false)
    public LocalDateTime createdAt;

    @PrePersist
    public void prePersist() {
        createdAt = LocalDateTime.now();
    }
}
