package ch.unige.events.entity;

import io.quarkus.hibernate.orm.panache.PanacheEntityBase;
import jakarta.persistence.*;

import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(
    name = "event_views",
    uniqueConstraints = @UniqueConstraint(
        name = "uq_event_view_user_event",
        columnNames = {"event_id", "user_id"}
    )
)
public class EventView extends PanacheEntityBase {

    // IDENTITY strategy maps to PostgreSQL "GENERATED BY DEFAULT AS IDENTITY",
    // which sets a database-level DEFAULT on the column. This allows the native
    // ON CONFLICT INSERT in EventViewService to omit the id column and still get
    // a valid auto-incremented value from the DB. The default AUTO strategy used
    // by PanacheEntity relies on a Hibernate-managed sequence with no DB-level
    // DEFAULT, which would cause a NOT NULL violation in native SQL inserts.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long id;

    @Column(name = "event_id", nullable = false)
    public Long eventId;

    @Column(name = "user_id", nullable = false)
    public UUID userId;

    @Column(name = "viewed_at", updatable = false)
    public LocalDateTime viewedAt;

    @PrePersist
    public void prePersist() {
        viewedAt = LocalDateTime.now();
    }
}
