apiVersion: v1
kind: Secret
metadata:
  name: doppler-token
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  serviceToken: {{ .Values.secrets.dopplerToken | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"ghcr.io\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.secrets.ghcrUsername .Values.secrets.ghcrPassword (printf "%s:%s" .Values.secrets.ghcrUsername .Values.secrets.ghcrPassword | b64enc) | b64enc }}
