quarkus.http.root-path=api
quarkus.http.port=8080

# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# Flyway
quarkus.flyway.migrate-at-start=true

# Dev
%dev.quarkus.datasource.username=${DB_USER:postgres}
%dev.quarkus.datasource.password=${DB_PASSWORD:postgres}
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:mydb}
%dev.quarkus.datasource.devservices.enabled=false

# %dev.quarkus.oidc.enabled=false
# %dev.quarkus.security.auth.enabled-in-dev-mode=false

# Prod
%prod.quarkus.datasource.username=${DB_USER}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

# OIDC
quarkus.oidc.auth-server-url=${OIDC_AUTH_SERVER_URL:https://placeholder.auth0.com}
quarkus.oidc.client-id=${OIDC_CLIENT_ID:placeholder-client-id}
quarkus.oidc.credentials.secret=${OIDC_CLIENT_SECRET:placeholder-secret}
quarkus.oidc.token.audience=${OIDC_AUDIENCE:your-custom-api-identifier}
quarkus.oidc.application-type=service

# Test
%test.quarkus.oidc.enabled=false
%test.quarkus.security.auth.enabled-in-dev-mode=false
%test.quarkus.datasource.active=false
%test.quarkus.hibernate-orm.active=false

# Swagger UI toujours visible (par défaut uniquement en dev)
quarkus.swagger-ui.always-include=true

# URL de la swagger UI
quarkus.swagger-ui.path=/swagger-ui

# URL du fichier OpenAPI JSON/YAML
quarkus.smallrye-openapi.path=/openapi

# Active le bouton "Authorize" dans Swagger UI
quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.security-scheme-name=bearerAuth