quarkus.http.root-path=${API_ROOT_PATH}
quarkus.http.port=${API_PORT}

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
quarkus.hibernate-orm.schema-management.strategy=update