quarkus.http.root-path=api
quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.datasource.devservices.reuse=true

%prod.quarkus.datasource.username=${DB_USER}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

# OIDC
quarkus.oidc.auth-server-url=${OIDC_AUTH_SERVER_URL:https://placeholder.auth0.com}
quarkus.oidc.client-id=${OIDC_CLIENT_ID:placeholder-client-id}
quarkus.oidc.application-type=service

%test.quarkus.oidc.enabled=false
%test.quarkus.security.auth.enabled-in-dev-mode=false
%test.quarkus.datasource.active=false
%test.quarkus.hibernate-orm.active=false