"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _event_cards from './event-cards.bones.json'
import _event_detail from './event-detail.bones.json'
import _event_edit from './event-edit.bones.json'
import _profile from './profile.bones.json'
import _search_results from './search-results.bones.json'
import _event_calendar from './event-calendar.bones.json'
import _user_identity_inline from './user-identity-inline.bones.json'
import _user_identity_card from './user-identity-card.bones.json'
import _my_publications from './my-publications.bones.json'
import _drafts_resume_strip from './drafts-resume-strip.bones.json'
import _event_stats from './event-stats.bones.json'
import _admin_reports from './admin-reports.bones.json'
import _admin_featured from './admin-featured.bones.json'
import _notification_panel from './notification-panel.bones.json'
import _co_organizers_section from './co-organizers-section.bones.json'
import _event_organizer_team from './event-organizer-team.bones.json'
import _comments from './comments.bones.json'
import _follow_list from './follow-list.bones.json'
import _feed_timeline from './feed-timeline.bones.json'
import _user_search_results from './user-search-results.bones.json'

registerBones({
  "event-cards": _event_cards,
  "event-detail": _event_detail,
  "event-edit": _event_edit,
  "profile": _profile,
  "search-results": _search_results,
  "event-calendar": _event_calendar,
  "user-identity-inline": _user_identity_inline,
  "user-identity-card": _user_identity_card,
  "my-publications": _my_publications,
  "drafts-resume-strip": _drafts_resume_strip,
  "event-stats": _event_stats,
  "admin-reports": _admin_reports,
  "admin-featured": _admin_featured,
  "notification-panel": _notification_panel,
  "co-organizers-section": _co_organizers_section,
  "event-organizer-team": _event_organizer_team,
  "comments": _comments,
  "follow-list": _follow_list,
  "feed-timeline": _feed_timeline,
  "user-search-results": _user_search_results,
})
