"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _event_cards from './event-cards.bones.json'
import _event_detail from './event-detail.bones.json'
import _event_edit from './event-edit.bones.json'
import _profile from './profile.bones.json'
import _search_results from './search-results.bones.json'
import _event_calendar from './event-calendar.bones.json'
import _user_identity_inline from './user-identity-inline.bones.json'
import _user_identity_card from './user-identity-card.bones.json'
import _my_publications from './my-publications.bones.json'

registerBones({
  "event-cards": _event_cards,
  "event-detail": _event_detail,
  "event-edit": _event_edit,
  "profile": _profile,
  "search-results": _search_results,
  "event-calendar": _event_calendar,
  "user-identity-inline": _user_identity_inline,
  "user-identity-card": _user_identity_card,
  "my-publications": _my_publications,
})
