"use client"
// Auto-generated by boneyard CLI — do not edit
// Regenerate with: npx boneyard-js build (dev server must be running)
import { registerBones } from 'boneyard-js/react'

import _event_cards from './event-cards.bones.json'
import _event_detail from './event-detail.bones.json'
import _profile from './profile.bones.json'

registerBones({
  "event-cards": _event_cards,
  "event-detail": _event_detail,
  "profile": _profile,
})
