apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: unige-events
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unige-events-tls
  namespace: unige-events
spec:
  secretName: unige-events-tls
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  ipAddresses:
    - 10.25.10.136