apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ip-redirect
  namespace: unige-events
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: https://10.25.10.136.nip.io
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: unige-events
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - 10.25.10.136.nip.io
      secretName: unige-events-tls
  rules:
    - host: 10.25.10.136.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
