apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: unige-events
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - 137.74.47.55.nip.io
      secretName: unige-events-tls
  rules:
    - host: 137.74.47.55.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80