apiVersion: v1
kind: Service
metadata:
  name: postgres-notification
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: postgres-notification
  ports:
    - port: 5432
      targetPort: 5432
