{{- if not .Values.postgres.shared }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-notification
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: postgres-notification
  replicas: 1
  selector:
    matchLabels:
      app: postgres-notification
  template:
    metadata:
      labels:
        app: postgres-notification
    spec:
      automountServiceAccountToken: false
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: unige_events_notifications
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER"]
            initialDelaySeconds: 5
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgres.storageSize }}

{{- end }}
