apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: kong
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
    - name: status
      port: 8100
      targetPort: 8100
