cloudflared:
  enabled: true
  mode: quick

postgres:
  storageSize: 512Mi
  shared: true
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
      ephemeral-storage: "128Mi"
    limits:
      memory: "256Mi"
      ephemeral-storage: "256Mi"

engagementService:
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
      ephemeral-storage: "128Mi"
    limits:
      memory: "256Mi"
      ephemeral-storage: "256Mi"

eventService:
  resources:
    requests:
      cpu: "50m"
      memory: "192Mi"
      ephemeral-storage: "128Mi"
    limits:
      memory: "384Mi"
      ephemeral-storage: "256Mi"

moderationService:
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
      ephemeral-storage: "128Mi"
    limits:
      memory: "256Mi"
      ephemeral-storage: "256Mi"

notificationService:
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
      ephemeral-storage: "128Mi"
    limits:
      memory: "256Mi"
      ephemeral-storage: "256Mi"

userService:
  resources:
    requests:
      cpu: "50m"
      memory: "192Mi"
      ephemeral-storage: "128Mi"
    limits:
      memory: "384Mi"
      ephemeral-storage: "256Mi"

minio:
  storageSize: 512Mi
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
      ephemeral-storage: "128Mi"
    limits:
      memory: "256Mi"
      ephemeral-storage: "256Mi"

web:
  resources:
    requests:
      cpu: "25m"
      memory: "32Mi"
      ephemeral-storage: "64Mi"
    limits:
      memory: "64Mi"
      ephemeral-storage: "128Mi"

kong:
  replicas: 1
  resources:
    requests:
      cpu: "50m"
      memory: "192Mi"
      ephemeral-storage: "64Mi"
    limits:
      memory: "256Mi"
      ephemeral-storage: "128Mi"

kafka:
  storageSize: 1Gi
  heapOpts: "-Xmx256m -Xms256m"
  resources:
    requests:
      cpu: "100m"
      memory: "384Mi"
      ephemeral-storage: "256Mi"
    limits:
      memory: "512Mi"
      ephemeral-storage: "512Mi"
