cloudflared:
  enabled: true
  mode: named

image:
  registry: ghcr.io
  org: unige-pinfo6-2026
  pullPolicy: Always
  tag: latest
  web:
    name: unige-events-web
    tag: latest

ingress:
  host: pinfo6.p-info.net

db:
  image: postgres:16
  storageSize: 1Gi
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
      ephemeral-storage: "256Mi"
    limits:
      memory: "512Mi"
      ephemeral-storage: "512Mi"

minio:
  image: "minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1"
  storageSize: 5Gi
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
      ephemeral-storage: "256Mi"
    limits:
      memory: "512Mi"
      ephemeral-storage: "512Mi"

web:
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
      ephemeral-storage: "128Mi"
    limits:
      memory: "128Mi"
      ephemeral-storage: "256Mi"

kong:
  image: kong:3.7.0
  replicas: 2
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
      ephemeral-storage: "128Mi"
    limits:
      memory: "256Mi"
      ephemeral-storage: "256Mi"

kafka:
  image: apache/kafka:3.7.0
  storageSize: 5Gi
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
      ephemeral-storage: "256Mi"
    limits:
      memory: "1Gi"
      ephemeral-storage: "1Gi"
