apiVersion: v1
kind: Service
metadata:
  name: stats-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: stats-service
spec:
  type: ClusterIP
  selector:
    app: stats-service
  ports:
    - port: 8080
      targetPort: 8080
