apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: api
          image: {{ .Values.image.registry }}/{{ .Values.image.org }}/{{ .Values.image.api.name }}:{{ .Values.image.api.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
            - name: S3_ENDPOINT
              value: http://minio:9000
          envFrom:
            - secretRef:
                name: app-secrets
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
