{{- if .Values.postgres.shared }}
apiVersion: v1
kind: Service
metadata:
  name: postgres-shared
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: postgres-shared
  ports:
    - port: 5432
      targetPort: 5432
{{- end }}
