name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    name: Deploy
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit