name: Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  cleanup-preview:
    name: Cleanup Preview
    runs-on: ubuntu-latest
    environment: preview
    concurrency:
      group: deploy-preview-${{ github.event.pull_request.number }}
      cancel-in-progress: false
    env:
      PR_NAMESPACE: unige-events-pr-${{ github.event.pull_request.number }}
      KUBECONFIG: /tmp/kubeconfig-${{ github.run_id }}

    steps:
      - name: Set kubectl context
        run: echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $KUBECONFIG

      - name: Cleanup
        run: |
          helm uninstall ${{ env.PR_NAMESPACE }} --namespace ${{ env.PR_NAMESPACE }} --ignore-not-found --timeout 3m || true
          kubectl delete namespace ${{ env.PR_NAMESPACE }} --ignore-not-found
